# 增加行长度限制，减少不必要的换行
max_width = 140
fn_call_width = 80
chain_width = 80
array_width = 80
struct_lit_width = 25
struct_variant_width = 50
attr_fn_like_width = 80
single_line_if_else_max_width = 80
single_line_let_else_max_width = 80
