#
# Copyright (c) 2025 SMALLPROGRAM <https://github.com/smallprogram>
# Description: Auto compile
#
name: "Build Bandix"
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
env:
  TZ: Asia/Shanghai

jobs:
  check_version:
    name: Check Version
    runs-on: ubuntu-latest
    outputs:
      latest_version: ${{ steps.check_version.outputs.latest_version }}
      has_update: ${{ steps.check_version.outputs.has_update }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - name: Check version
        id: check_version
        env:
          url_tags: https://api.github.com/repos/${{ github.repository }}/releases/latest
        run: |
          latest_version=v$(grep '^version' bandix/Cargo.toml | awk -F '"' '{print $2}')
          echo "latest_version=${latest_version}" >> $GITHUB_OUTPUT

          remote_latest_version=$(wget -qO- -t1 -T2 ${{env.url_tags}} | jq -r '.tag_name')
          echo "remote_latest_version=${remote_latest_version}" >> $GITHUB_OUTPUT

          if [ -z "$remote_latest_version" ] || [ "$remote_latest_version" = "null" ]; then
            echo "Failed to fetch remote tags"
            echo "has_update=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "Remote latest: $remote_latest_version"

          if [ "$latest_version" = "$remote_latest_version" ]; then
            echo "has_update=false" >> $GITHUB_OUTPUT
          else
            echo "has_update=true" >> $GITHUB_OUTPUT
          fi

  install_dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    needs: check_version
    if: needs.check_version.outputs.has_update == 'true'
    outputs:
      status: ${{ steps.install_dependencies.outputs.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - name: Install dependencies
        id: install_dependencies
        run: |
          chmod +x ./install_dependencies.sh
          sudo ./install_dependencies.sh
          df -H
          echo "status=success" >> $GITHUB_OUTPUT

  build_bandix:
    name: Build Bandix
    runs-on: ubuntu-latest
    needs: [check_version, install_dependencies]
    if: needs.check_version.outputs.has_update == 'true' && needs.install_dependencies.outputs.status == 'success'
    outputs:
      status: ${{ steps.build_bandix.outputs.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - name: Build bandix ${{ needs.check_version.outputs.latest_version }}
        id: build_bandix
        run: |
          chmod +x ./build_release.sh
          sudo ./build_release.sh
          df -H
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-files
          path: release/
          retention-days: 1

  prepare_release:
    name: Prepare Release
    runs-on: ubuntu-latest
    needs: [check_version, build_bandix]
    if: needs.check_version.outputs.has_update == 'true' && needs.build_bandix.outputs.status == 'success'
    outputs:
      status: ${{ steps.prepare_release.outputs.status }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-files
          path: release/

      - name: Prepare release
        id: prepare_release
        run: |
          echo "![](https://img.shields.io/github/downloads/${{ github.repository }}/${{needs.check_version.outputs.latest_version}}/total?style=flat-square)" >> release.txt
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Upload release files
        uses: actions/upload-artifact@v4
        with:
          name: release-package
          path: |
            release.txt
            release/
          retention-days: 1

  generate_release:
    name: Generate Release
    runs-on: ubuntu-latest
    needs: [check_version, prepare_release]
    if: needs.check_version.outputs.has_update == 'true' && needs.prepare_release.outputs.status == 'success'
    steps:
      - name: Download release files
        uses: actions/download-artifact@v4
        with:
          name: release-package

      - name: Generate new tag & release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{needs.check_version.outputs.latest_version}}
          body_path: release.txt
          files: release/*